export const teamData = [
  {
    id: 1,
    name: "Habtamu Tsegaye Tola",
    role: "Founder and CEO",
    description:
      "Guiding Hummfly Tech with vision and innovation, Habtamu ensures the company consistently delivers impactful digital solutions.",
    image: "/images/habtamu.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 2,
    name: "Natnael Tadesse Kebede",
    role: " DevOps Engineer and QA Tester",
    description:
      "With expertise in cloud administration, DevOps engineering, and system automation, Natnaelt brings a wealth of knowledge to streamline product development and drive innovation.",
    image: "/images/natty.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },

  {
    id: 4,
    name: "Ebba Birhanu",
    role: "Frontend Developer",
    description: "Expert in creating dynamic and responsive user interfaces, ensuring seamless user experiences",
    image: "/images/ebba.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 9,
    name: "Hana Guta",
    role: " UI/UX Designer",
    description: "Creating intuitive and user-friendly designs that enhance engagement and usability.",
    image: "/images/hana.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 10,
    name: "Ermias Assefa Yegnanew",
    role: "Graphics Designer",
    description: "Ensuring visually compelling designs that align with brand and project goals.",
    image: "/images/ermi.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 11,
    name: "Naol Sileshi ",
    role: "Marketing Specialist",
    description: "Strategizing and executing campaigns to connect with our target audience.",
    image: "/images/naol.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 8,
    name: "Etsub Taye",
    role: "Mobile App Developer",
    description: "Developing mobile solutions tailored to client needs and market trends.",
    image: "/images/etsub.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 6,
    name: "Sofonyas Tizazu Engda ",
    role: "Backend Developer",
    description: "Specialist in building robust and scalable backend systems to power our application",
    image: "/images/sofi.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 5,
    name: "Ephraim Debel Negassa",
    role: " Frontend Developer",
    description: "Focused on delivering visually appealing and functional front-end solutions.",
    image: "/images/ephrem.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 7,
    name: "Dagim Mesfin Seifu",
    role: "Mobile App Developer",
    description: "Dedicated to crafting intuitive and efficient mobile applications..",
    image: "/images/dagim.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },

  {
    id: 12,
    name: "Daniel Ababu ",
    role: "Social Media Manager",
    description: "Crafting engaging social media strategies to amplify Hummfly Tech’s digital presence.",
    image: "/images/daniel.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
  {
    id: 3,
    name: "Desalegn Tamirat",
    role: " Marketing Specialist",
    description:
      "With a background in software engineering and product management, Misgana combines technical expertise with strategic insight to oversee projects from inception to completion, ensuring precision, efficiency, and alignment with client goals while driving innovation and success.",
    image: "/images/desalegn.png",
    socialLinks: {
      mail: "#",
      phone: "#",
      linkedin: "#",
      facebook: "#",
    },
  },
];
